{
 "title": "Pozo",
 "time": { "from": "now-1M/M", "to": "now-1M/M" },
 "panels": [
  {
   "title": "Niveles",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Nivel de agua",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  (6000 - distance) / 1000 AS distance\nFROM mt_sondapozo\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Volumen total",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  (6000 - distance) * 3.1415926 * 1.5 *1.5 / 1000 AS volumen\nFROM mt_sondapozo\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Volumen disponible",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  (4000 - distance) * 3.1415926 * 1.5 *1.5 / 1000 AS volumen\nFROM mt_sondapozo\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Batería",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  bateria\nFROM mt_sondapozo\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Altura pozo",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  (6000 - distance) / 1000 AS distance\nFROM mt_sondapozo\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Evolución semanal altura pozo",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "rawSql": "SELECT\nDISTINCT(time_bucket('1 week', t.time)) AS time,\n  avg(t.distance) AS dmed,\n  min(t.distance) AS dmin,\n  max(t.distance) AS dmax\nfrom(\nSELECT\n  \"time\" AS \"time\",\n  (6000 - distance) / 1000 AS distance\nFROM mt_sondapozo\nWHERE\n  $__timeFilter(\"time\")\n  ) as t\ngroup by 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Evolución mensualaltura pozo",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "rawSql": "SELECT\nDISTINCT(time_bucket('1 month', t.time)) AS time,\n  avg(t.distance) AS dmed,\n  min(t.distance) AS dmin,\n  max(t.distance) AS dmax\nfrom(\nSELECT\n  \"time\" AS \"time\",\n  (6000 - distance) / 1000 AS distance\nFROM mt_sondapozo\nWHERE\n  $__timeFilter(\"time\")\n  ) as t\ngroup by 1\nORDER BY 1"
    }
   ]
  },
  { "title": "Comunicaciones", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "SNR",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  snr\nFROM mt_sondapozo\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  rssi\nFROM mt_sondapozo\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Distribución de frecuencias (MHz)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "  SELECT\n    NOW() as time,\n    (round(frequency/1000000.0, 1))::text as metric,\n    count(*) as value\n  FROM mt_sondapozo\n  group by frequency\n  order by frequency asc;\n "
    }
   ]
  },
  {
   "title": "Frecuencia",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "kHz" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  frequency/1000 as frequency\nFROM mt_sondapozo\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  }
 ]
}